project:
  type: website
  output-dir: docs

website:
  title: "Sierra's Site"
  site-url: https://github.com/smattair/smattair.github.io.git
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - projects.qmd
      - resume.qmd
  page-footer:
    background: light # or 'dark'
    left: Copyright 2025, Sierra Mattair
    right: This website is built with {{< fa heart title="a heart" >}} and [{{< fa brands github title="GitHub octocat logo" >}}](https://github.com/smattair){target=blank}
format:
  html:
    theme:
      light: minty
      dark: solar
    css: styles.css
    toc: true
    page-layout: full

editor: visual

