project:
  type: website
  output-dir: docs

website:
  title: "Sierra's Site"
  site-url: https://smattair.github.io/
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - projects.qmd
      - resume.qmd


format:
  html:
    theme:
      light: minty
      dark: solar
    css: styles.css
    toc: true
    page-layout: full

editor: visual

